openapi: 3.0.3
info:
  title: Dokumen API Cloud Function - OpenAPI 3.0
  description: >-
    Jelaskan disini apa saja yang perlu dijelaskan
    termasuk informasi yang diperlukan untuk dinilai
    term of service isi dari link repo dari swagger ini
  termsOfService: https://github.com/jscroot/examples/tree/main/api/swagger
  contact:
    email: awangga@gmail.com
  license:
    name: Peda Package
    url: https://pkg.go.dev/github.com/petapedia/peda
  version: 1.0.11
externalDocs:
  description: Repo GCF
  url: https://petapedia.github.io/gcf/
servers:
  - url: https://asia-southeast2-civil-epigram-429004-t8.cloudfunctions.net/webhook
tags:
  - name: data
    description: Data Geo Spasial
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/get/
  - name: auth
    description: Auth to Access to API
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://petapedia.github.io/gcf/post/
  - name: user
    description: Get Token and Authorize
paths:
  /petapedia:
    get:
      tags:
        - data
      summary: Get Data Geospasial
      description: List Data Geospasial
      operationId: getGeoJSON
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peta'
        '400':
          description: Invalid status value
  /petapedia-post:
    post:
      tags:
        - auth
      summary: Login get Token
      description: Login and Get User Token
      operationId: authService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '405':
          description: Invalid input
      security:
        - token:
            - write:apiKey
            - read:apiKey
  /geoquery:
    post:
      tags:
        - auth
      summary: Get Lokasi dari titik kordinat
      description: Login and Get User Token
      operationId: authService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '405':
          description: Invalid input
      security:
        - token:
            - write:apiKey
            - read:apiKey
  /petapedia-create:
    post:
      tags:
        - data
      summary: Create New Data
      description: Add new geospatial data
      operationId: createGeoData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peta'
      responses:
        '201':
          description: Data created successfully
        '400':
          description: Invalid input
  /petapedia-update:
    put:
      tags:
        - data
      summary: Update Geospatial Data
      description: Update existing geospatial data
      operationId: updateGeoData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peta'
      responses:
        '200':
          description: Data updated successfully
        '400':
          description: Invalid input
  /petapedia-delete:
    delete:
      tags:
        - data
      summary: Delete Geospatial Data
      description: Remove existing geospatial data
      operationId: deleteGeoData
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID of the data to delete
      responses:
        '200':
          description: Data deleted successfully
        '400':
          description: Invalid ID supplied
components:
  schemas:
    Peta:
      type: object
      properties:
        type:
          type: string
        geometry:
          type: object
          properties:
            type: 
              type: string
            coordinates: 
              type: array
              items:
                type: number
        properties:
          type: object
          properties:
            name:
              type: string
    Auth:
      type: object
      properties:
        username:
          type: string
          example: petped
        password:
          type: string
          example: secret
    AuthResponse:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: fehguy
        token:
          type: string
          example: fehguy
  requestBodies:
    AuthReq:
      description: Request Authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Auth'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AuthResponse'
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: header
